[package]
name = "l0ttie"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
# https://github.com/LottieFiles/dotlottie-rs/issues/318
dotlottie-rs = { git = "https://github.com/LottieFiles/dotlottie-rs.git", tag = "v0.1.42", features = [
    "thorvg-v0",
] }
frei0r-rs = { git = "https://github.com/rectalogic/frei0r-rs.git", tag = "1.0.0" }
